# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_make_memberships_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
