# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_auto_20170615_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='password',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
