# Generated by Django 2.0.3 on 2018-04-29 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_collective_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
