# Generated by Django 2.0.3 on 2018-06-11 21:55

from django.db import migrations


def forwards_func(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("purchases", "UserProfile")

    for user in User.objects.all():
        try:
            UserProfile.objects.get(user=user)
        except UserProfile.DoesNotExist:
            UserProfile.objects.create(user=user)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_alter_field_currency_on_liquidation'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
