# Generated by Django 2.0.3 on 2018-06-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_add_userprofiles_to_existing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
