# Generated by Django 2.0.3 on 2018-06-13 21:30

from django.db import migrations, models

from payshare.purchases.models import DEFAULT_AVATAR_URL


def forwards_func(apps, schema_editor):
    UserProfile = apps.get_model("purchases", "UserProfile")

    for profile in UserProfile.objects.filter(avatar_image_url__isnull=True):
        profile.avatar_image_url = DEFAULT_AVATAR_URL
        profile.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_allow_longer_user_avatar_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_image_url',
            field=models.CharField(blank=True, default='https://avataaars.io/?avatarStyle=Circle&topType=NoHair&accessoriesType=Blank&facialHairType=Blank&clotheType=ShirtCrewNeck&clotheColor=Black&eyeType=Default&eyebrowType=DefaultNatural&mouthType=Default&skinColor=Light', max_length=1024, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
