# Generated by Django 2.0.3 on 2018-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_add_default_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='currency_symbol',
            field=models.CharField(default='€', max_length=3),
        ),
    ]
