# Generated by Django 2.0.3 on 2019-09-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
    ]
