# Generated by Django 2.2.5 on 2019-09-04 19:46

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0017_collective_readonly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidation',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10),
        ),
    ]
