# Generated by Django 2.2.5 on 2019-09-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_auto_20190904_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paypal_me_username',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
