# Generated by Django 2.2.5 on 2019-09-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0020_collective_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collective',
            old_name='logo_url',
            new_name='logo_image',
        ),
    ]
