# Generated by Django 2.2.10 on 2022-09-17 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("purchases", "0022_purchaseweight"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="weights",
            field=models.ManyToManyField(
                related_name="weighted_members",
                through="purchases.PurchaseWeight",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
